packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@astryxdesign/build": 0.3.0
  "@astryxdesign/cli": 0.3.0
  "@astryxdesign/core": 0.3.0
  "@astryxdesign/theme-neutral": 0.3.0
  "@babel/core": ^8.0.1
  "@stylexjs/babel-plugin": 0.19.0
  "@stylexjs/stylex": 0.19.0
  "@stylexjs/unplugin": 0.19.0
  "@tanstack/react-router": 1.170.31
  "@tanstack/react-start": 1.168.48
  "@tanstack/router-cli": 1.167.32
  "@types/node": ^24
  "@types/react": 19.2.18
  "@types/react-dom": 19.2.4
  "@vitejs/plugin-react": 6.0.5
  react: 19.2.8
  react-dom: 19.2.8
  typescript: ^7.0.2
  unplugin: 2.3.11
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
overrides:
  vite: "catalog:"
  "@types/node": "catalog:"
  typescript: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  "@astryxdesign/cli": true
  "@astryxdesign/core": true
  esbuild: true
  lightningcss: true
