import { defineConfig } from 'vite-plus';

export default defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    // harness/fixtures/** holds Fixture material, not app code: before-states are snapshots of
    // generated pages that only resolve inside a prepared worktree. Checking them here type-checks
    // them against the wrong context and reports errors that are not real. Generated code is
    // always evaluated in situ - see harness/AGENTS.md.
    ignorePatterns: [
      '**/routeTree.gen.ts',
      '**/dist/**',
      '**/dist-ssr/**',
      'coverage/**',
      'harness/fixtures/**',
    ],
    arrowParens: 'always',
    bracketSameLine: false,
    bracketSpacing: true,
    embeddedLanguageFormatting: 'auto',
    endOfLine: 'lf',
    htmlWhitespaceSensitivity: 'css',
    insertFinalNewline: true,
    jsdoc: {
      addDefaultToDescription: true,
      bracketSpacing: false,
      capitalizeDescriptions: true,
      commentLineStrategy: 'singleLine',
      descriptionTag: false,
      descriptionWithDot: false,
      keepUnparsableExampleIndent: false,
      lineWrappingStyle: 'greedy',
      preferCodeFences: true,
      separateReturnsFromParam: true,
      separateTagGroups: true,
    },
    jsxSingleQuote: false,
    objectWrap: 'preserve',
    printWidth: 100,
    proseWrap: 'preserve',
    quoteProps: 'as-needed',
    semi: true,
    singleAttributePerLine: false,
    singleQuote: true,
    sortImports: {
      groups: [
        'builtin',
        { newlinesBetween: true },
        'external',
        ['internal', 'subpath'],
        ['parent', 'sibling', 'index'],
        'style',
        'unknown',
      ],
      ignoreCase: true,
      internalPattern: ['#/'],
      newlinesBetween: true,
      order: 'asc',
      partitionByComment: true,
      partitionByNewline: false,
      sortSideEffects: false,
    },
    sortPackageJson: {
      sortScripts: false,
    },
    svelte: false,
    tabWidth: 2,
    trailingComma: 'all',
    useTabs: false,
    vueIndentScriptAndStyle: false,
    overrides: [
      {
        files: ['*.json', '*.jsonc'],
        options: {
          trailingComma: 'none',
        },
      },
      {
        files: ['*.md', '*.mdx'],
        options: {
          proseWrap: 'always',
        },
      },
    ],
  },
  lint: {
    // harness/fixtures/** holds Fixture material, not app code: before-states are snapshots of
    // generated pages that only resolve inside a prepared worktree. Checking them here type-checks
    // them against the wrong context and reports errors that are not real. Generated code is
    // always evaluated in situ - see harness/AGENTS.md.
    ignorePatterns: [
      '**/routeTree.gen.ts',
      '**/dist/**',
      '**/dist-ssr/**',
      'coverage/**',
      'harness/fixtures/**',
    ],
    jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
    env: {
      browser: true,
      builtin: true,
      node: true,
    },
    plugins: [
      'eslint',
      'typescript',
      'react',
      'jsx-a11y',
      'import',
      'vitest',
      'promise',
      'node',
      'unicorn',
      'oxc',
      'react-perf',
      'jsdoc',
    ],
    categories: {
      correctness: 'error',
      suspicious: 'error',
      perf: 'error',
      pedantic: 'off',
      style: 'off',
      restriction: 'off',
      nursery: 'off',
    },
    settings: {
      react: {
        version: '19.2.8',
      },
      vitest: {
        typecheck: true,
      },
    },
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error',
      'react/react-in-jsx-scope': 'off',
      'react/only-export-components': ['error', { allowConstantExport: true }],
      'react-perf/jsx-no-new-array-as-prop': 'off',
      'react-perf/jsx-no-new-function-as-prop': 'off',
      'react-perf/jsx-no-new-object-as-prop': 'off',
      'no-console': 'error',
      complexity: 'off',
      'max-lines': 'off',
      'max-lines-per-function': 'off',
      'max-depth': 'off',
      'max-nested-callbacks': 'off',
      'max-statements': 'off',
      'no-nested-ternary': 'error',
      'no-underscore-dangle': 'error',
      'oxc/branches-sharing-code': 'off',
      'unicorn/catch-error-name': 'error',
      'unicorn/consistent-date-clone': 'error',
      'unicorn/consistent-empty-array-spread': 'error',
      'unicorn/consistent-existence-index-check': 'error',
      'unicorn/consistent-function-scoping': 'error',
      'unicorn/consistent-template-literal-escape': 'error',
      'unicorn/custom-error-definition': 'error',
      'unicorn/error-message': 'error',
      'unicorn/explicit-length-check': 'error',
      'unicorn/filename-case': ['error', { case: 'kebabCase' }],
      'unicorn/new-for-builtins': 'error',
      'unicorn/no-abusive-eslint-disable': 'error',
      'unicorn/no-accessor-recursion': 'error',
      'unicorn/no-anonymous-default-export': 'error',
      'unicorn/no-array-callback-reference': 'error',
      'unicorn/no-array-method-this-argument': 'error',
      'unicorn/no-array-reverse': 'error',
      'unicorn/no-array-sort': 'error',
      'unicorn/no-await-in-promise-methods': 'error',
      'unicorn/no-console-spaces': 'error',
      'unicorn/no-document-cookie': 'error',
      'unicorn/no-empty-file': 'error',
      'unicorn/no-hex-escape': 'error',
      'unicorn/no-instanceof-array': 'error',
      'unicorn/no-instanceof-builtins': 'error',
      'unicorn/no-invalid-fetch-options': 'error',
      'unicorn/no-invalid-remove-event-listener': 'error',
      'unicorn/no-length-as-slice-end': 'error',
      'unicorn/no-magic-array-flat-depth': 'error',
      'unicorn/no-negation-in-equality-check': 'error',
      'unicorn/no-new-array': 'error',
      'unicorn/no-new-buffer': 'error',
      'unicorn/no-object-as-default-parameter': 'error',
      'unicorn/no-process-exit': 'error',
      'unicorn/no-single-promise-in-promise-methods': 'error',
      'unicorn/no-static-only-class': 'error',
      'unicorn/no-thenable': 'error',
      'unicorn/no-this-assignment': 'error',
      'unicorn/no-typeof-undefined': 'error',
      'unicorn/no-unnecessary-array-flat-depth': 'error',
      'unicorn/no-unnecessary-array-splice-count': 'error',
      'unicorn/no-unnecessary-await': 'error',
      'unicorn/no-unnecessary-slice-end': 'error',
      'unicorn/no-unreadable-array-destructuring': 'error',
      'unicorn/no-unreadable-iife': 'error',
      'unicorn/no-useless-collection-argument': 'error',
      'unicorn/no-useless-error-capture-stack-trace': 'error',
      'unicorn/no-useless-fallback-in-spread': 'error',
      'unicorn/no-useless-length-check': 'error',
      'unicorn/no-useless-promise-resolve-reject': 'error',
      'unicorn/no-useless-spread': 'error',
      'unicorn/no-useless-switch-case': 'error',
      'unicorn/no-useless-undefined': 'error',
      'unicorn/no-zero-fractions': 'error',
      'unicorn/number-literal-case': 'error',
      'unicorn/numeric-separators-style': 'error',
      'unicorn/prefer-add-event-listener': 'error',
      'unicorn/prefer-array-find': 'error',
      'unicorn/prefer-array-flat-map': 'error',
      'unicorn/prefer-array-index-of': 'error',
      'unicorn/prefer-array-some': 'error',
      'unicorn/prefer-bigint-literals': 'error',
      'unicorn/prefer-class-fields': 'error',
      'unicorn/prefer-classlist-toggle': 'error',
      'unicorn/prefer-code-point': 'error',
      'unicorn/prefer-date-now': 'error',
      'unicorn/prefer-dom-node-append': 'error',
      'unicorn/prefer-dom-node-dataset': 'error',
      'unicorn/prefer-dom-node-remove': 'error',
      'unicorn/prefer-dom-node-text-content': 'error',
      'unicorn/prefer-global-this': 'error',
      'unicorn/prefer-import-meta-properties': 'error',
      'unicorn/prefer-includes': 'error',
      'unicorn/prefer-keyboard-event-key': 'error',
      'unicorn/prefer-math-min-max': 'error',
      'unicorn/prefer-math-trunc': 'error',
      'unicorn/prefer-modern-dom-apis': 'error',
      'unicorn/prefer-modern-math-apis': 'error',
      'unicorn/prefer-module': 'error',
      'unicorn/prefer-native-coercion-functions': 'error',
      'unicorn/prefer-negative-index': 'error',
      'unicorn/prefer-node-protocol': 'error',
      'unicorn/prefer-number-properties': 'error',
      'unicorn/prefer-object-from-entries': 'error',
      'unicorn/prefer-optional-catch-binding': 'error',
      'unicorn/prefer-prototype-methods': 'error',
      'unicorn/prefer-query-selector': 'error',
      'unicorn/prefer-regexp-test': 'error',
      'unicorn/prefer-response-static-json': 'error',
      'unicorn/prefer-set-size': 'error',
      'unicorn/prefer-spread': 'error',
      'unicorn/prefer-string-raw': 'error',
      'unicorn/prefer-string-replace-all': 'error',
      'unicorn/prefer-string-slice': 'error',
      'unicorn/prefer-string-starts-ends-with': 'error',
      'unicorn/prefer-string-trim-start-end': 'error',
      'unicorn/prefer-structured-clone': 'error',
      'unicorn/prefer-type-error': 'error',
      'unicorn/relative-url-style': 'error',
      'unicorn/require-array-join-separator': 'error',
      'unicorn/require-module-attributes': 'error',
      'unicorn/require-module-specifiers': 'error',
      'unicorn/require-number-to-fixed-digits-argument': 'error',
      'unicorn/require-post-message-target-origin': 'error',
      'unicorn/text-encoding-identifier-case': 'error',
      'unicorn/throw-new-error': 'off',
      'import/default': 'error',
      'import/first': 'error',
      'import/namespace': 'error',
      'import/newline-after-import': 'error',
      'import/no-absolute-path': 'error',
      'import/no-amd': 'error',
      'import/no-commonjs': 'error',
      'import/no-cycle': 'off',
      'import/no-duplicates': 'error',
      'import/no-dynamic-require': 'error',
      'import/no-empty-named-blocks': 'error',
      'import/no-mutable-exports': 'error',
      'import/no-named-as-default': 'error',
      'import/no-named-as-default-member': 'error',
      'import/no-self-import': 'error',
      'import/no-unassigned-import': ['error', { allow: ['**/*.css'] }],
      'import/no-webpack-loader-syntax': 'error',
      'typescript/adjacent-overload-signatures': 'error',
      'typescript/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': true,
          'ts-nocheck': true,
          'ts-check': false,
          minimumDescriptionLength: 12,
        },
      ],
      'typescript/ban-tslint-comment': 'error',
      'typescript/consistent-generic-constructors': 'error',
      'typescript/consistent-indexed-object-style': 'error',
      'typescript/consistent-return': 'off',
      'typescript/consistent-type-assertions': 'error',
      'typescript/consistent-type-definitions': ['error', 'interface'],
      'typescript/consistent-type-exports': 'error',
      'typescript/consistent-type-imports': 'error',
      'typescript/dot-notation': 'error',
      'typescript/no-confusing-non-null-assertion': 'error',
      'typescript/no-confusing-void-expression': 'error',
      'typescript/no-deprecated': 'error',
      'typescript/no-dynamic-delete': 'error',
      'typescript/no-empty-interface': 'error',
      'typescript/no-empty-object-type': 'error',
      'typescript/no-explicit-any': 'error',
      'typescript/no-extraneous-class': 'error',
      'typescript/no-import-type-side-effects': 'error',
      'typescript/no-inferrable-types': 'error',
      'typescript/no-invalid-void-type': 'error',
      'typescript/no-misused-promises': 'error',
      'typescript/no-mixed-enums': 'error',
      'typescript/no-namespace': 'error',
      'typescript/no-non-null-asserted-nullish-coalescing': 'error',
      'typescript/no-non-null-assertion': 'error',
      'typescript/no-require-imports': 'error',
      'typescript/no-unnecessary-boolean-literal-compare': 'error',
      'typescript/no-unnecessary-condition': 'error',
      'typescript/no-unnecessary-qualifier': 'error',
      'typescript/no-unnecessary-template-expression': 'error',
      'typescript/no-unnecessary-type-arguments': 'error',
      'typescript/no-unnecessary-type-assertion': 'error',
      'typescript/no-unnecessary-type-constraint': 'error',
      'typescript/no-unnecessary-type-conversion': 'error',
      'typescript/no-unnecessary-type-parameters': 'error',
      'typescript/no-unsafe-argument': 'error',
      'typescript/no-unsafe-assignment': 'error',
      'typescript/no-unsafe-call': 'error',
      'typescript/no-unsafe-enum-comparison': 'error',
      'typescript/no-unsafe-function-type': 'error',
      'typescript/no-unsafe-member-access': 'error',
      'typescript/no-unsafe-return': 'error',
      'typescript/no-unsafe-type-assertion': 'error',
      'typescript/no-useless-empty-export': 'error',
      'typescript/no-var-requires': 'error',
      'typescript/no-wrapper-object-types': 'error',
      'typescript/non-nullable-type-assertion-style': 'error',
      'typescript/only-throw-error': 'error',
      'typescript/prefer-as-const': 'error',
      'typescript/prefer-enum-initializers': 'error',
      'typescript/prefer-find': 'error',
      'typescript/prefer-for-of': 'error',
      'typescript/prefer-function-type': 'error',
      'typescript/prefer-includes': 'error',
      'typescript/prefer-literal-enum-member': 'error',
      'typescript/prefer-nullish-coalescing': 'error',
      'typescript/prefer-readonly': 'error',
      'typescript/prefer-reduce-type-parameter': 'error',
      'typescript/prefer-regexp-exec': 'error',
      'typescript/prefer-return-this-type': 'error',
      'typescript/prefer-string-starts-ends-with': 'error',
      'typescript/prefer-ts-expect-error': 'error',
      'typescript/related-getter-setter-pairs': 'error',
      'typescript/restrict-plus-operands': 'error',
      'typescript/return-await': 'error',
      'typescript/strict-boolean-expressions': 'error',
      'typescript/switch-exhaustiveness-check': 'error',
      'typescript/unified-signatures': 'error',
      'typescript/use-unknown-in-catch-callback-variable': 'error',
    },
    options: {
      denyWarnings: true,
      typeAware: true,
      typeCheck: true,
      reportUnusedDisableDirectives: 'error',
      respectEslintDisableDirectives: true,
    },
    overrides: [
      {
        files: ['apps/web/src/routes/**/*'],
        rules: {
          // TanStack Router owns route-module HMR and requires the exported Route contract.
          'react/only-export-components': 'off',
          // TanStack Router's file-based routing conventions (__root, $param, etc.) aren't
          // free-form naming.
          'unicorn/filename-case': 'off',
          // Astryx composes page shells through slot props: `header={<LayoutHeader…>}`,
          // `icon={<Icon…/>}`, `actions={…}`. The rule is satisfiable (hoist to a module
          // constant, or useMemo) but only by writing against the vendor's own idiom - all 14
          // of Astryx's page templates use the inline form. Enforcing it here would buy a
          // memoization ritual at the cost of idiomatic composition, on static shells where
          // the re-render saving is negligible. Its three siblings (jsx-no-new-array/function/
          // object-as-prop) are already off above for the same class of reason. Still enforced
          // outside routes, where it catches real re-render cost.
          'react-perf/jsx-no-jsx-as-prop': 'off',
        },
      },
      {
        // The Instrument is a CLI: printing a Run's result is its output, not a stray debug
        // statement. Fixture folders follow @vercel/agent-eval's contract (PROMPT.md, EVAL.ts),
        // which mandates names this repo's kebab-case rule would otherwise reject.
        files: ['harness/**/*'],
        rules: {
          'no-console': 'off',
          'unicorn/filename-case': 'off',
        },
      },
      {
        files: [
          '**/*.spec.js',
          '**/*.spec.jsx',
          '**/*.spec.mjs',
          '**/*.spec.mjsx',
          '**/*.spec.ts',
          '**/*.spec.tsx',
          '**/*.spec.mts',
          '**/*.spec.mtsx',
          '**/*.test.js',
          '**/*.test.jsx',
          '**/*.test.mjs',
          '**/*.test.mjsx',
          '**/*.test.ts',
          '**/*.test.tsx',
          '**/*.test.mts',
          '**/*.test.mtsx',
        ],
        rules: {
          'vitest/consistent-each-for': 'error',
          'vitest/consistent-test-it': 'error',
          'vitest/consistent-vitest-vi': 'error',
          'vitest/hoisted-apis-on-top': 'error',
          'vitest/no-alias-methods': 'error',
          'vitest/no-commented-out-tests': 'error',
          'vitest/no-conditional-expect': 'error',
          'vitest/no-conditional-in-test': 'error',
          'vitest/no-conditional-tests': 'error',
          'vitest/no-disabled-tests': 'error',
          'vitest/no-duplicate-hooks': 'error',
          'vitest/no-focused-tests': 'error',
          'vitest/no-hooks': 'error',
          'vitest/no-identical-title': 'error',
          'vitest/no-import-node-test': 'error',
          'vitest/no-interpolation-in-snapshots': 'error',
          'vitest/no-large-snapshots': 'error',
          'vitest/no-mocks-import': 'error',
          'vitest/no-standalone-expect': 'error',
          'vitest/no-test-prefixes': 'error',
          'vitest/no-test-return-statement': 'error',
          'vitest/no-unneeded-async-expect-function': 'error',
          'vitest/prefer-called-once': 'error',
          'vitest/prefer-called-times': 'error',
          'vitest/prefer-called-with': 'error',
          'vitest/prefer-comparison-matcher': 'error',
          'vitest/prefer-equality-matcher': 'error',
          'vitest/prefer-expect-resolves': 'error',
          'vitest/prefer-expect-type-of': 'error',
          'vitest/prefer-importing-vitest-globals': 'off',
          'vitest/prefer-lowercase-title': 'error',
          'vitest/prefer-snapshot-hint': 'error',
          'vitest/prefer-strict-boolean-matchers': 'error',
          'vitest/prefer-strict-equal': 'error',
          'vitest/prefer-to-be': 'error',
          'vitest/prefer-to-be-falsy': 'error',
          'vitest/prefer-to-be-object': 'error',
          'vitest/prefer-to-be-truthy': 'error',
          'vitest/prefer-to-contain': 'error',
          'vitest/prefer-to-have-been-called-times': 'error',
          'vitest/prefer-to-have-length': 'error',
          'vitest/prefer-todo': 'error',
          'vitest/require-awaited-expect-poll': 'error',
          'vitest/require-local-test-context-for-concurrent-snapshots': 'error',
          'vitest/require-mock-type-parameters': 'error',
          'vitest/require-to-throw-message': 'error',
          'vitest/valid-expect': 'error',
          'vitest/valid-expect-in-promise': 'error',
          'vitest/valid-title': 'error',
          'vitest/warn-todo': 'error',
        },
      },
    ],
  },
  run: {
    cache: true,
  },
});
