import { defineTheme } from '@astryxdesign/core/theme';
import { neutralTheme } from '@astryxdesign/theme-neutral/built';
import {
  ArrowDownIcon,
  ArrowSquareOutIcon,
  ArrowsDownUpIcon,
  ArrowUpIcon,
  CalendarIcon,
  CaretDoubleLeftIcon,
  CaretDoubleRightIcon,
  CaretDownIcon,
  CaretLeftIcon,
  CaretRightIcon,
  CheckCircleIcon,
  CheckIcon,
  ChecksIcon,
  ClockIcon,
  ColumnsIcon,
  CopyIcon,
  DotsThreeIcon,
  EyeSlashIcon,
  FunnelIcon,
  InfoIcon,
  ListIcon,
  MagnifyingGlassIcon,
  MicrophoneIcon,
  StopIcon,
  WarningIcon,
  WrenchIcon,
  XCircleIcon,
  XIcon,
} from '@phosphor-icons/react';

// Every semantic icon name Astryx components can request (`astryx docs icons`),
// mapped to Phosphor so the whole app renders one icon set instead of mixing
// Astryx's per-theme defaults with whatever a component author reaches for.
export const appTheme = defineTheme({
  name: 'phosphor',
  extends: neutralTheme,
  icons: {
    close: <XIcon />,
    chevronDown: <CaretDownIcon />,
    chevronLeft: <CaretLeftIcon />,
    chevronRight: <CaretRightIcon />,
    chevronsLeft: <CaretDoubleLeftIcon />,
    chevronsRight: <CaretDoubleRightIcon />,
    check: <CheckIcon />,
    success: <CheckCircleIcon />,
    error: <XCircleIcon />,
    warning: <WarningIcon />,
    info: <InfoIcon />,
    calendar: <CalendarIcon />,
    clock: <ClockIcon />,
    externalLink: <ArrowSquareOutIcon />,
    menu: <ListIcon />,
    moreHorizontal: <DotsThreeIcon />,
    search: <MagnifyingGlassIcon />,
    arrowUp: <ArrowUpIcon />,
    arrowDown: <ArrowDownIcon />,
    arrowsUpDown: <ArrowsDownUpIcon />,
    funnel: <FunnelIcon />,
    eyeSlash: <EyeSlashIcon />,
    viewColumns: <ColumnsIcon />,
    copy: <CopyIcon />,
    checkDouble: <ChecksIcon />,
    wrench: <WrenchIcon />,
    stop: <StopIcon />,
    microphone: <MicrophoneIcon />,
  },
});
